#spring:
#  batch:
#    job:
#      enabled: false
#  hadoop:
#    fsUri: hdfs://localhost:8020
#    resourceManagerHost: localhost
#example:
#  inputLocalDir: data
#  inputFileName: tweets.dat
#  inputDir: /tmp/hashtags/input
#  outputDir: /tmp/hashtags/output
#  sparkAssembly: hdfs:///app/spark/spark-assembly-1.5.0-hadoop2.6.0.jar